# Numpy 
Numpy Numerical Python (NumPy) is an open source Python library for scientific computing. NumPy provides a host of features that allow a Python programmer to work with high-performance arrays and matrices.
Following are some features of Numpy


    - Numerical Python
    - Numerical Array
    - Fastest 
    - Vectorize Operation
    - Contigious Memory
    

In [1]:
#importing numpy llibrary
import numpy as np

In [3]:
#creating a number array
#creating an array using a python list
x = np.array([11,22,33,44,55])
x

array([11, 22, 33, 44, 55])

### Now we will apply some operation or functions on this numpy array

In [4]:
x.size

5

In [6]:
#shape of the array
x.shape

(5,)

(5, ) it means it is one dimensional array 1d array

In [7]:
#dimension will also be check throgh ndim
x.ndim

1

In [9]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Same as we have in python of range function
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Both has same output but numpy has array and python has list output.

# 2 dimensional array

In [11]:
arr2d = np.array([[11,22,33],[44,55,66],[77,88,99]])
arr2d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [12]:
#Now apply the operations
arr2d.shape

(3, 3)

Here 3 rows and 3 columns

In [13]:
#dimensions
arr2d.ndim

2

In [14]:
arr2d.size

9

### Now we will use .reshape() to create some numpy arrays

In [17]:
arr = np.arange(20).reshape(5,4)
arr
#We can create the following array with arange(20)
# arr2d = np.arange(20).reshape(20,1)
# arr2d = np.arange(20).reshape(4,5)
# arr2d = np.arange(20).reshape(10,10)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.size

20

In [20]:
arr.ndim

2

In [21]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# 3d array let have practics some 3d arrays

In [24]:
arr3d = np.arange(64).reshape(4,4,4) #4 is depth, row and columns
arr3d
#Here 9 is depth and second 4 is row and third 4 is columns

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [28]:
arr3darray = np.arange(144).reshape(9,4,4)
arr3darray
#Here 9 is depth and 4 is row and 4 is columns

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]],

       [[ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79]],

       [[ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]],

       [[128, 129, 130, 

### Now we are checking the slicing and indexing with the numpy array

In [29]:
arr3darray[1,3]

array([28, 29, 30, 31])

In [31]:
arr3darray[4,2]

array([72, 73, 74, 75])

In [36]:
arr3darray[7:]

array([[[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]],

       [[128, 129, 130, 131],
        [132, 133, 134, 135],
        [136, 137, 138, 139],
        [140, 141, 142, 143]]])

In [37]:
arr3darray[: 2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [38]:
arr3darray[1][2]

array([24, 25, 26, 27])

In [40]:
arr3darray[3][2]

array([56, 57, 58, 59])

In [41]:
arr3darray[8][2]

array([136, 137, 138, 139])